server:
  port: 8016

spring:
  application:
    name: msvc-gateway
  output:
    ansi:
      enabled: ALWAYS
  cloud:
    gateway:
      mvc:
        routes:
          - id: msOrquest
            uri: http://localhost:8080
            predicates:
              - Path=/api/Orquestador/**
          - id: msDominio
            uri: http://localhost:8032
            predicates:
              - Path=/api/Usuarios/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/

